export const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
};

export const GMAIL_API_BASE_URL = "https://gmail.googleapis.com/gmail/v1";

export const COMMON_EMAIL_PROVIDERS = [
  "gmail.com",
  "yahoo.com",
  "outlook.com",
  "hotmail.com",
  "aol.com",
  "icloud.com",
];

export const COMMON_SERVICES = [
  "youtube.com",
  "linkedin.com",
  "facebook.com",
  "twitter.com",
  "instagram.com",
  "github.com",
  "stackoverflow.com",
  "medium.com",
  "amazonaws.com",
  "google.com",
  "microsoft.com",
  "apple.com",
  "calendly.com",
  "zoom.us",
  "dropbox.com",
  "slack.com",
  "notion.so",
  "figma.com",
  "canva.com",
];

export const RELEVANT_ATTACHMENT_TYPES = [
  "application/pdf",
  "image/jpeg",
  "image/jpg",
  "image/png",
  "image/gif",
  "text/html",
  "text/plain",
];

export const COUNTRY_MAPPING: Record<string, string> = {
  "united kingdom": "GB",
  "great britain": "GB",
  england: "GB",
  scotland: "GB",
  wales: "GB",
  uk: "GB",
  "united states": "US",
  usa: "US",
  america: "US",
  canada: "CA",
  australia: "AU",
  germany: "DE",
  france: "FR",
  japan: "JP",
  "south korea": "KR",
  korea: "KR",
  india: "IN",
  brazil: "BR",
  mexico: "MX",
  netherlands: "NL",
  sweden: "SE",
  switzerland: "CH",
  italy: "IT",
  spain: "ES",
  indonesia: "ID",
  "new zealand": "NZ",
  singapore: "SG",
  "hong kong": "HK",
  taiwan: "TW",
  philippines: "PH",
  "south africa": "ZA",
  malaysia: "MY",
  thailand: "TH",
  vietnam: "VN",
  nigeria: "NG",
};

export const TLD_TO_COUNTRY: Record<string, string> = {
  uk: "GB",
  ca: "CA",
  au: "AU",
  de: "DE",
  fr: "FR",
  jp: "JP",
  kr: "KR",
  in: "IN",
  br: "BR",
  mx: "MX",
  nl: "NL",
  se: "SE",
  ch: "CH",
  it: "IT",
  es: "ES",
  id: "ID",
  nz: "NZ",
  sg: "SG",
  hk: "HK",
  tw: "TW",
  ph: "PH",
  za: "ZA",
  my: "MY",
  th: "TH",
  vn: "VN",
  ng: "NG",
};

export const COUNTRY_NAMES: Record<string, string> = {
  US: "United States",
  GB: "United Kingdom",
  CA: "Canada",
  AU: "Australia",
  DE: "Germany",
  FR: "France",
  JP: "Japan",
  KR: "South Korea",
  IN: "India",
  BR: "Brazil",
  MX: "Mexico",
  NL: "Netherlands",
  SE: "Sweden",
  CH: "Switzerland",
  IT: "Italy",
  ES: "Spain",
  ID: "Indonesia",
  NZ: "New Zealand",
  SG: "Singapore",
  HK: "Hong Kong",
  TW: "Taiwan",
  PH: "Philippines",
  ZA: "South Africa",
  MY: "Malaysia",
  TH: "Thailand",
  VN: "Vietnam",
  NG: "Nigeria",
};

export const VALID_STATUSES = [
  "applied",
  "next_step",
  "interview",
  "offer",
  "rejected",
  "accepted",
];
